# Site settings
title: Katsuhiro Tanaka
email: k-tanaka [at] g.ecc.u-tokyo.ac.jp
description: Personal page of Katsuhiro Tanaka
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katsu-tanaka.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
